#!/usr/bin/with-contenv bashio

set -e

bashio::log.info "Starting MiniDLNA Server..."

# Port z HA ingress konfigurace
PORT=$(bashio::addon.ingress_port)
MINIDLNA_PORT=8201
bashio::log.info "Nginx proxy port: ${PORT}, MiniDLNA internal port: ${MINIDLNA_PORT}"

# Načtení konfigurace
FRIENDLY_NAME=$(bashio::config 'friendly_name')
INOTIFY=$(bashio::config 'inotify')
NOTIFY_INTERVAL=$(bashio::config 'notify_interval')
STRICT_DLNA=$(bashio::config 'strict_dlna')
ENABLE_SUBTITLES=$(bashio::config 'enable_subtitles')
LOG_LEVEL=$(bashio::config 'log_level')
WIDE_LINKS=$(bashio::config 'wide_links')
ROOT_CONTAINER=$(bashio::config 'root_container')
FORCE_RESCAN=$(bashio::config 'force_rescan')

# Konverze bool na yes/no pro minidlna.conf
bool_to_yesno() {
    if [ "$1" = "true" ]; then echo "yes"; else echo "no"; fi
}

# Force rescan - smazání databáze
if [ "${FORCE_RESCAN}" = "true" ]; then
    bashio::log.info "Force rescan enabled - removing existing database..."
    rm -rf /data/db/*
fi

# Vytvoření adresářů
mkdir -p /data/db
mkdir -p /var/log/minidlna

# Generování minidlna.conf
{
    echo "# Auto-generated by Home Assistant MiniDLNA add-on"
    echo "port=${MINIDLNA_PORT}"
    echo "user=root"
    echo ""

    # Media directories
    for i in $(bashio::config 'media_dirs|keys'); do
        MEDIA_DIR=$(bashio::config "media_dirs[${i}]")

        # Validace cesty
        DIR_PATH="${MEDIA_DIR##*,}"
        if [ ! -d "${DIR_PATH}" ]; then
            bashio::log.warning "Media directory '${DIR_PATH}' does not exist (from '${MEDIA_DIR}')"
        fi

        echo "media_dir=${MEDIA_DIR}"
    done

    echo ""
    echo "friendly_name=${FRIENDLY_NAME}"
    echo "db_dir=/data/db"
    echo "log_dir=/var/log/minidlna"
    echo "inotify=$(bool_to_yesno "${INOTIFY}")"
    echo "notify_interval=${NOTIFY_INTERVAL}"
    echo "strict_dlna=$(bool_to_yesno "${STRICT_DLNA}")"
    echo "enable_subtitles=$(bool_to_yesno "${ENABLE_SUBTITLES}")"
    echo "log_level=${LOG_LEVEL}"
    echo "wide_links=$(bool_to_yesno "${WIDE_LINKS}")"
    echo "root_container=${ROOT_CONTAINER}"
    echo ""
    echo "album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg"
} > /etc/minidlna.conf

bashio::log.info "MiniDLNA configuration:"
cat /etc/minidlna.conf

# Generování nginx.conf - proxy řeší DNS rebinding (přepisuje Host header)
cat > /etc/nginx/nginx.conf << EOF
worker_processes 1;
error_log stderr warn;
pid /var/run/nginx.pid;

events {
    worker_connections 64;
}

http {
    access_log off;

    server {
        listen ${PORT};

        location / {
            proxy_pass http://127.0.0.1:${MINIDLNA_PORT};
            proxy_set_header Host 127.0.0.1:${MINIDLNA_PORT};
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_buffering off;
        }
    }
}
EOF

# Spuštění MiniDLNA jako daemon (respektuje log_level z configu)
bashio::log.info "Starting MiniDLNA daemon on port ${MINIDLNA_PORT}..."
minidlnad -f /etc/minidlna.conf -P /var/run/minidlna.pid

# Spuštění nginx proxy (předává requesty MiniDLNA s přepsaným Host headerem)
bashio::log.info "Starting nginx proxy on port ${PORT}..."
tail -F /var/log/minidlna/minidlna.log &
exec nginx -g 'daemon off;'
