#!/usr/bin/with-contenv bashio

set -e

bashio::log.info "Starting MiniDLNA (ReadyMedia) server..."

# Načtení konfigurace
FRIENDLY_NAME=$(bashio::config 'friendly_name')
INOTIFY=$(bashio::config 'inotify')
NOTIFY_INTERVAL=$(bashio::config 'notify_interval')
STRICT_DLNA=$(bashio::config 'strict_dlna')
ENABLE_SUBTITLES=$(bashio::config 'enable_subtitles')
LOG_LEVEL=$(bashio::config 'log_level')
WIDE_LINKS=$(bashio::config 'wide_links')
ROOT_CONTAINER=$(bashio::config 'root_container')
FORCE_RESCAN=$(bashio::config 'force_rescan')

# Port z HA ingress konfigurace (shodný s ports v config.json)
PORT=$(bashio::addon.ingress_port)
bashio::log.info "MiniDLNA will listen on port ${PORT}"

# Konverze bool na yes/no pro minidlna.conf
bool_to_yesno() {
    if [ "$1" = "true" ]; then
        echo "yes"
    else
        echo "no"
    fi
}

# Force rescan - smazání databáze
if [ "${FORCE_RESCAN}" = "true" ]; then
    bashio::log.info "Force rescan enabled - removing existing database..."
    rm -rf /data/db/*
fi

# Vytvoření adresáře pro databázi a logy
mkdir -p /data/db
mkdir -p /var/log/minidlna

# Detekce IP adres pro DNS rebinding workaround
# MiniDLNA kontroluje Host header proti listening_ip - přidáme localhost i reálnou IP
HOST_IP=$(hostname -i 2>/dev/null | awk '{print $1}' || echo "")

# Generování minidlna.conf
{
    echo "# Auto-generated by Home Assistant MiniDLNA add-on"
    echo "# Do not edit manually"
    echo ""
    echo "port=${PORT}"
    echo ""

    # Listening IP - localhost pro ingress proxy + reálná IP pro DLNA klienty
    echo "listening_ip=127.0.0.1"
    if [ -n "${HOST_IP}" ] && [ "${HOST_IP}" != "127.0.0.1" ]; then
        echo "listening_ip=${HOST_IP}"
    fi
    echo ""

    # Media directories
    for i in $(bashio::config 'media_dirs|keys'); do
        MEDIA_DIR=$(bashio::config "media_dirs[${i}]")

        # Validace cesty - extrahovat cestu za čárkou
        DIR_PATH="${MEDIA_DIR##*,}"
        if [ ! -d "${DIR_PATH}" ]; then
            bashio::log.warning "Media directory '${DIR_PATH}' does not exist (from '${MEDIA_DIR}')"
        fi

        echo "media_dir=${MEDIA_DIR}"
    done

    echo ""
    echo "friendly_name=${FRIENDLY_NAME}"
    echo "db_dir=/data/db"
    echo "log_dir=/var/log/minidlna"
    echo "inotify=$(bool_to_yesno "${INOTIFY}")"
    echo "notify_interval=${NOTIFY_INTERVAL}"
    echo "strict_dlna=$(bool_to_yesno "${STRICT_DLNA}")"
    echo "enable_subtitles=$(bool_to_yesno "${ENABLE_SUBTITLES}")"
    echo "log_level=${LOG_LEVEL}"
    echo "wide_links=$(bool_to_yesno "${WIDE_LINKS}")"
    echo "root_container=${ROOT_CONTAINER}"
    echo ""
    echo "# Album art filenames"
    echo "album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg"
} > /etc/minidlna.conf

bashio::log.info "Configuration generated:"
cat /etc/minidlna.conf

bashio::log.info "Starting MiniDLNA daemon..."

# Spuštění minidlna jako daemon (bez -d = respektuje log_level, žádný debug spam)
minidlnad -f /etc/minidlna.conf -P /var/run/minidlna.pid

# Výstup logů na stdout pro HA
exec tail -F /var/log/minidlna/minidlna.log
